version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo